when@prod:
  sentry:
    dsn: "%env(SENTRY_DSN)%"
    register_error_listener: false
    register_error_handler: false
    options:
      traces_sample_rate: 0.1
      ignore_exceptions:
        - 'Symfony\Component\ErrorHandler\Error\FatalError'
        - 'Symfony\Component\Debug\Exception\FatalErrorException'
  monolog:
    handlers:
      sentry_fingers_crossed:
        type: fingers_crossed
        action_level: error
        handler: sentry
        excluded_http_codes: [404, 405]
        buffer_size: 50
      sentry:
        type: sentry
        level: !php/const Monolog\Logger::ERROR
        hub_id: Sentry\State\HubInterface
        fill_extra_context: true
        process_psr_3_messages: false
