version: '3'

services:
  php:
    build:
      context: ./docker
    user: '${USER_ID}:${GROUP_ID}'
    container_name: maxicash_php
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated