version: '3'

services:
  php:
    image: grafikart/php:php8.2-2
    user: '${USER_ID}:${GROUP_ID}'
    container_name: maxicash_php
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated