controllers:
  resource: ../src/
  type: attribute
  schemes:
    - HTTP
    - HTTPS

api_login_check:
  path: /api/login_check

api_refresh_token:
  path: /api/token/refresh

api_token_invalidate:
  path: /api/token/invalidate
