controllers:
  resource: ../src/
  type: attribute
  schemes:
    - HTTP
    - HTTPS

identity_and_access_login_check:
  path: /api/login_check

identity_and_access_refresh_token:
  path: /api/token/refresh

identity_and_access_token_invalidate:
  path: /api/token/invalidate
