name: Tests
on: [ push ]
jobs:
    unit-tests:
        name: unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer:v2

            - name: Setup cache
              run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
            - name: Cache dependencies installed with composer
              uses: actions/cache@v2
              with:
                  path: ${{ env.COMPOSER_CACHE_DIR }}
                  key: php8.3-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      php8.3-composer-latest-
            - name: Update composer
              run: composer self-update
            - name: Install dependencies with composer
              run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            - name: Run units tests
              run: composer app:tests
              env:
                  APP_ENV: test
